version: "3.7"
services:

deskshare:
    image: containous/whoami
    labels:
      - traefik.http.routers.whoami.rule=Host(`deskshare.tstsrv.de`)
      - traefik.http.routers.whoami.entrypoints=https
      - traefik.http.routers.whoami.tls=true
      - traefik.http.routers.whoami.tls.certresolver=${CERT_RESOLVER}
