version: "3.7"
services:
  database:
    networks:
     - max_intern
    image: mysql:8.0
    container_name: dsapi_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 23131001
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"   
    volumes:
     - ./db-dump:/docker-entrypoint-initdb.d
    ports:
    - "3306:3306"
  api:
    networks:
     - max_intern
    build: ./DeskShareApi
    container_name: dsapi
    ports:
      - "9977:9977"
      - "9978:9978"
    command: ["./wait-for-it.sh", "database:3306", "--", "dotnet", "DeskShareApi.dll"]
    links:
      - database
    depends_on:
      - database
  client:
    networks:
     - tstsrv_default 
     - max_intern 
    labels:
      - traefik.enable=true
      - traefik.http.routers.deskshare.rule=Host(`deskshare.tstsrv.de`)
      - traefik.http.routers.deskshare.entrypoints=https
      - traefik.http.routers.deskshare.tls=true
      - traefik.http.routers.deskshare.tls.certresolver=letsencrypt     
    build: ./DeskShare
    container_name: dsclient
    ports:
      - "80:80"
      - "443:443"
    command: ["./wait-for-it.sh", "api:80", "--", "dotnet", "DeskShare.dll"]
    links:
      - api
    depends_on:
      - api
    environment:
      TZ: "Europe/Berlin"
networks:
  tstsrv_default:
    external: true
  max_intern:
    external: false