version: "3.9"
services:

  database:
    image: mysql:8.0
    container_name: dsapi_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 23131001
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    security_opt:
     - seccomp:unconfined
    volumes:
     - ./db-dump:/docker-entrypoint-initdb.d
    networks:
     - tstsrv_default
    ports:
     - "3306:3306"

  api:
    build: ./DeskShareApi
    networks: 
      - tstsrv_default
    labels:
      - traefik.enable=true
      - traefik.http.routers.deskshare.rule=Host(`deskshare.tstsrv.de`)
      - traefik.http.routers.deskshare.entrypoints=https
      - traefik.http.routers.deskshare.tls=true
      - traefik.http.routers.deskshare.tls.certresolver=letsencrypt
    ports:
      - "8080:8080"
    links:
      - database

networks:
  tstsrv_default:
    external: true
