version: "3.7"
 
services:  
  database:   
    image: mysql:8.0
    container_name: dsapi_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 23131001
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"   
    volumes:
     - ./db-dump:/docker-entrypoint-initdb.d
    ports:
    - "3306:3306"
    environment:
      TZ: "Europe/Berlin"
  api:  
    build: ./DeskShareApi
    container_name: dsapi
    ports:
      - "9977:9977"
      - "9978:9978"
    links:
      - database
    environment:
      TZ: "Europe/Berlin"
  client:  
    build: ./DeskShare
    container_name: dsclient
    ports:
      - "80:80"
      - "443:443"
    links:
      - api
    environment:
      TZ: "Europe/Berlin"
