version: "3.7" 
services:  
  database:   
    image: mysql:8.0
    container_name: dsapi_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 23131001
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"   
    volumes:
     - ./db-dump:/docker-entrypoint-initdb.d
    ports:
    - "3306:3306"
  api:  
    build: ./DeskShareApi
    container_name: dsapi
    ports:
      - "9977:9977"
      - "9978:9978"
    command: ["./wait-for-it.sh", "database:3306", "--", "dotnet", "DeskShareApi.dll"]
    links:
      - database
    depends_on:
      - database
  client:  
    build: ./DeskShare
    container_name: dsclient
    ports:
      - "80:80"
      - "443:443"
    command: ["./wait-for-it.sh", "api:80", "--", "dotnet", "DeskShare.dll"]
    links:
      - api
    depends_on:
      - api
    environment:
      TZ: "Europe/Berlin"
